name: Check and Build Docker Image

on:
  workflow_dispatch:     # 手动触发
  push:
    tags:
      - 'v*'  # 监听以 v 开头的标签

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: "code-server"  # 镜像名称
      DOCKER_TAG: ${{ github.ref_name }}  # 镜像标签
      DOCKERFILE_PATH: "./code-server.dockerfile"  # 自定义 Dockerfile 路径
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 使用 docker/build-push-action 来构建并推送镜像
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .                  # 构建上下文路径，默认为当前目录
          push: true                 # 是否推送到 Docker Hub
          platforms: linux/amd64,linux/arm64
          file: ${{ env.DOCKERFILE_PATH }}  # 指定自定义 Dockerfile 的路径
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}  # >使用环境变量作为镜像标签
